// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int32
	AuthorID  int32
	ParentID  int32
	Slug      string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IsHidden  bool
}

type Migration struct {
	Name string
}

type Post struct {
	ID             int32
	Title          string
	Slug           string
	Poster         string
	Tags           []string
	Short          string
	Body           string
	AuthorID       int32
	PublishedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AuthorUsername string
	IsEditorsPick  bool
}

type User struct {
	ID                  int32
	Username            string
	Email               string
	Password            string
	Roles               []string
	EmailToken          string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	SendVerifiedEmailAt pgtype.Timestamptz
	ResetPwdToken       string
	RptExpiredAt        pgtype.Timestamptz
	IsBlocked           bool
}
