create table if not exists users (
    id int generated by default as identity primary key,
	username text not null default '',
    email text not null default '',
    password text not null default '',
    first_name text not null default '',
    last_name text not null default '',
    roles text[] not null default '{}',
    email_token text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default '0001-01-01 00:00:00',
    send_verified_email_at timestamptz not null default '0001-01-01 00:00:00',
	reset_pwd_token text not null default '',
	rpt_expired_at timestamp with time zone not null default '0001-01-01 00:00:00'
);

create unique index if not exists idx_users_username on users using btree(username) where username <> '';
create unique index if not exists idx_users_email on users using btree(email) where email <> '';
