create table if not exits posts (
    id int generated by default as identity primary key,
	title text not null default '',
    slug text not null default '',
    poster text not null default '',
    tags text[] not null default '{}',
    short text not null default '',
    body text not null default '',
	publisher_id int not null,
    published_at timestamptz not null default '0001-01-01 00:00:00',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default '0001-01-01 00:00:00'
);

create unique index if not exists idx_posts_slug on posts using btree(slug) where slug <> '';
create index if not exists idx_posts_publisher_id on posts using btree(publisher_id) where publisher_id > 0;
