create table if not exists archive (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	origin_id int NOT NULL DEFAULT 0,
	payload jsonb NOT NULL DEFAULT '{}' ::jsonb,
	deleted_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	origin_table text NOT NULL DEFAULT ''
);

CREATE OR REPLACE FUNCTION to_archive ()
	RETURNS TRIGGER
	LANGUAGE plpgsql
	AS $$
BEGIN
	EXECUTE 'insert into archive (payload, origin_id, origin_table) VALUES ($1, $2, $3)'
	USING to_jsonb (OLD.*),
	OLD.id,
	TG_TABLE_NAME;
	RETURN OLD;
END;
$$;

CREATE TRIGGER if not exists archive_post_trigger
	AFTER DELETE ON posts
	FOR EACH ROW
	EXECUTE FUNCTION to_archive ();